/**
 * universal search engine
 * universal search engine api
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Object1 { 
    /**
     * This will be the object id of the clicked object
     */
    objectClickedOn?: string;
    /**
     * This will be id of the user who clicked the object
     */
    clickedByUser?: string;
}
