/**
 * universal search engine
 * universal search engine api
 *
 * OpenAPI spec version: 1.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SearchParameters {
    /**
     *  a preFilter script applied before aggregation
     */
    preFilter?: string;
    /**
     * a dictionary of key, value where key is category name, and value is array of accepted filters
     * applied after aggregation
     */
    postFilters?: any;
    /**
     * page number for pagination
     */
    page?: number;
    /**
     * size of aggregations to be returned
     */
    aggregationSize?: number;

    [key: string]: any;
}
